services:
  # Postgres Database Service
  postgres:
    container_name: postgres16_monolith
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  # Postgres Database UI Service
  pgadmin:
    container_name: pgadmin4_monolith
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  # Zipkin Service
  zipkin:
    container_name: zipkin-c
    image: openzipkin/zipkin:3
    ports:
      - "9411:9411"
    networks:
      - postgres

# Network
networks:
  postgres:
    driver: bridge

# Volumes
volumes:
  postgres:
  pgadmin: