spring:
  application:
    name: company-microservice
  profiles:
    active:
      - prod

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

# ZIPKIN TRACING
management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8082