spring:
  application:
    name: review-microservice
  profiles:
    active:
      - prod

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://localhost:8761/eureka

server:
  port: 8082