spring:
  application:
    name: review-microservice
  profiles:
    active:
      - prod

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8083