spring:
  application:
    name: config-server
  profiles:
    active:
      - prod

server:
  port: 8085

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0